---
- name: Install pip
  apt: name=python-pip state=present

- name: Install deps
  command: pip install {{ item }}
  with_items:
    - docker-compose==1.9.0

- name: Run service
  docker_service:
    project_name: marathon-lb
    definition:
      version: '2'
      services:
        marathon-lb:
          restart: always
          # pull: yes
          image: mesosphere/marathon-lb
          command: "poll --marathon http://0.0.0.0:8080/ --group '*' --haproxy-map"
          network_mode: host
          environment:
            POLL_INTERVAL: 10
            PORTS: 9090
