---
- name: Install mesosphere package
  apt:
    name: "{{item}}"
    state: present
    allow_unauthenticated: yes 
    force: yes
  with_items:
    - 'mesos'

- name: Configure ZK for mesos
  template:
    dest: "{{ item }}"
    src: templates/mesos-zk.j2
  with_items:
    - /etc/mesos/zk

- name: Configure quorum
  template:
    dest: /etc/mesos-master/quorum
    src: templates/quorum.j2

- name: Configure master ips
  template:
    dest: /etc/mesos-master/{{ item }}
    src: templates/master-{{ item }}.j2
  with_items:
    - ip
    - hostname

- name: Configure slave ips
  template:
    dest: /etc/mesos-slave/{{ item }}
    src: templates/slave-{{ item }}.j2
  with_items:
    - ip
    - hostname

- name: Configure containerizers
  lineinfile:
    create: yes
    dest: /etc/mesos-slave/containerizers
    line: docker,mesos

- name: Configure docker timeout
  lineinfile:
    create: yes
    dest: /etc/mesos-slave/executor_registration_timeout
    line: 10mins

- name: Configure slave defaults
  template:
    dest: /etc/default/mesos-slave
    src: templates/default-mesos-slave.j2
