---
- name: Make sure slave service is running
  systemd: name={{ item }} state=started enabled=yes
  with_items:
    - mesos-slave

- name: Make sure master services are stopped
  systemd: name=mesos-master state=stopped enabled=no
  with_items:
    - mesos-master
    - marathon
    - zookeeper
